### ISSUE TITLE
Add DiagonalCoulombHamiltonian

### ISSUE THREAD

**Issue by kevinsung** [qiskit-community/ffsim#117]
This is a Hamiltonian with a diagonal Coulomb term. See Eq. (1) of https://arxiv.org/pdf/1711.04789.pdf. We can absorb the "number" term into the one body-part.

We can use the corresponding class in [OpenFermion](https://github.com/quantumlib/OpenFermion/blob/master/src/openfermion/ops/representations/diagonal_coulomb_hamiltonian.py) as a reference.

The implementation should be similar to [MolecularHamiltonian](https://github.com/qiskit-community/ffsim/blob/main/python/ffsim/hamiltonians/molecular_hamiltonian.py) or [DoubleFactorizedHamiltonian](https://github.com/qiskit-community/ffsim/blob/main/python/ffsim/hamiltonians/double_factorized_hamiltonian.py). Something like this:

```python
@dataclasses.dataclass(frozen=True)
class DiagonalCoulombHamiltonian:
    one_body_tensor: np.ndarray
    diag_coulomb_mat: np.ndarray
```

We can add a method
```python
@staticmethod
def from_fermion_operator(op: FermionOperator) -> DiagonalCoulombHamiltonian
```
to initialize from a compatible FermionOperator, like the Hubbard model. Passing a FermionOperator with incompatible terms should raise an error.

**Comment by bartandrews** [comment]
I would like to help out with this!
